#spring:
#  datasource:
#    url: jdbc:sqlserver://serverbacksql.database.windows.net:1433;databaseName=DBSQLBACKAZURE;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: deivid
#    password: arswsqlback31.
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    show-sql: true
#    hibernate:
#      dialect : org.hibernate.dialect.SQLServer2012Dialect
#
#server:
#  port: 9191
